server:
   port: 3001
db:
   default:
       adapter: mongodb
       params:
           host: localhost
           port: 27017
           username: user
           password: password
           dbname: database
           charset: utf8
logger:
   transports:
       console:
           colorize: true
           prettyPrint: true
           label: planner
           handleExceptions: true
           level: warn
       file:
           filename:
           label: planner
           level: warn
           handleExceptions: true
           json: false