
source :rubygems
#Development tools for debugging the application
gem 'debugger'
gem 'bundler'
### Require Rack compatible gems
gem "rack"
gem "thin", "~> 1.5.1"
#gem "webrick"
#gem "ebb"
#gem "fcgi"
#gem "scgi"
#gem "mongrel"
#gem "passenger"
#A Ruby framework for rapid API development with great conventions.
gem "grape"
### easy XMPP client gem based on EventMachine
gem 'blather', '~> 0.8.5'
### JSON
gem 'json'
###BTM - Business Transaction Manager
gem 'commonity-btm',
    :require => 'btm',
    :path    => "./module/gems/btm/"
gem 'mongo'
gem 'ruote'
gem 'ruote-mon'
### Mongoid is an ODM (Object Document Mapper)
## Framework for MongoDB, written in Ruby.
gem "mongoid", "~> 3.1.4"

